name: AutoQuake
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.12.6
  - pandas>=1.1
  - h5py>=3.1
  - obspy>=1.3.1
  - tqdm>=4.52
  - scipy>=1.9
  - bottleneck>=1.3
  - tensorflow=2.7.0
  - pip
  - pip:
    - nest_asyncio>=1.5.3
    - tensorflow-io-gcs-filesystem==0.31.0
    - torch>=1.10.0
    - seisbench
    - git+https://github.com/wayneweiqiang/GaMMA.git
